# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8bb5b67047ca5e52f1ab186273083d1c90f0ba044b74f8920cc465cce0894fe5f85e847dd00a1b8209f2ee48b526885f85a2d250a2734ffd3b2db7299ff59f

test:
  secret_key_base: 2d7482b93f81272a2ecd96f5a7b733525281efa9f2b68e64ee9c256c2f42cacba9bcb1cf0b094acc06c0e37f4f8a7bff278be5417a370a6d68078dbd283b1c0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
